format: xs-configuration-v1
templates:
  sections:
    frontends: "@solenopsys/tp-frontends"
    backends: "@solenopsys/tp-backends"
    tools: "@solenopsys/tp-tools"
    contracts: "@solenopsys/tp-contracts"
    embedded: "@solenopsys/tp-embedded"
    engineering: "@solenopsys/tp-engineering"
  creation: {}
builders:
  front:
    - frontends/bootstraps
  module:
    - frontends/modules
  frontlib:
    - frontends/libraries
  helm:
    - backends/deployments
  library:
    - backends/libraries
  container:
    - backends/modules
processors:
  ts_injector:
    description: Injects source code location to tsconfig.json file
    triggers:
      - type: post
        sections:
          - frontends
        command:
          - code
          - add